package statecharts

// StateDefinitionID preserves whether a state's ID was written explicitly
// or generated by the builder. A generated ID may have an empty Value before
// validation/canonicalization; normalization assigns it deterministically on
// a private clone and never mutates caller-owned input.
type StateDefinitionID struct {
	Value     Identifier `json:"value,omitempty"`
	Generated bool       `json:"generated,omitempty"`
}

// TransitionType describes SCXML external versus internal transition entry
// semantics. The zero value means TransitionExternal.
type TransitionType string

const (
	TransitionExternal TransitionType = "external"
	TransitionInternal TransitionType = "internal"
)

// DataBinding controls when declarations receive their initial values.
// The zero value means DataBindingEarly.
type DataBinding string

const (
	// DataBindingEarly initializes every declaration when a session starts.
	DataBindingEarly DataBinding = "early"
	// DataBindingLate initializes a declaration immediately before its owning
	// state is entered for the first time.
	DataBindingLate DataBinding = "late"
)

// DataDefinition declares one model-owned data item. Source, Expr, and
// Content are mutually exclusive initialization modes; all three may be
// absent to declare an initially empty item. Declarations retain their order.
type DataDefinition struct {
	ID      Identifier  `json:"id"`
	Source  string      `json:"source,omitempty"`
	Expr    *Expression `json:"expr,omitempty"`
	Content *Expression `json:"content,omitempty"`
}

func (d DataDefinition) clone() DataDefinition {
	d.Expr = cloneExpression(d.Expr)
	d.Content = cloneExpression(d.Content)
	return d
}

func cloneDataDefinitions(definitions []DataDefinition) []DataDefinition {
	if definitions == nil {
		return nil
	}
	clone := make([]DataDefinition, len(definitions))
	for i := range definitions {
		clone[i] = definitions[i].clone()
	}
	return clone
}

// Definition is a complete, syntax-neutral statechart program. It is mutable
// authoring/inspection data, unlike the immutable compiled Chart. Definition
// contains no callbacks, runtime pointers, compiled indexes, or syntax bytes.
type Definition struct {
	ID           Identifier       `json:"id"`
	Name         string           `json:"name,omitempty"`
	Datamodel    Identifier       `json:"datamodel"`
	RevisionSalt string           `json:"revisionSalt,omitempty"`
	DataBinding  DataBinding      `json:"dataBinding,omitempty"`
	Data         []DataDefinition `json:"data,omitempty"`
	Root         StateDefinition  `json:"root"`
}

// StateDefinition describes one state-tree node in document order.
type StateDefinition struct {
	ID          StateDefinitionID      `json:"id"`
	Kind        StateKind              `json:"kind"`
	History     HistoryKind            `json:"history,omitempty"`
	Initial     *TransitionDefinition  `json:"initial,omitempty"`
	OnEntry     []ExecutableBlock      `json:"onEntry,omitempty"`
	OnExit      []ExecutableBlock      `json:"onExit,omitempty"`
	Transitions []TransitionDefinition `json:"transitions,omitempty"`
	Invokes     []InvokeDefinition     `json:"invokes,omitempty"`
	Data        []DataDefinition       `json:"data,omitempty"`
	DoneData    *DoneDataDefinition    `json:"doneData,omitempty"`
	Children    []StateDefinition      `json:"children,omitempty"`
}

// TransitionDefinition preserves event, target, condition, executable-block,
// and transition-type ordering. Empty Events means eventless; empty Targets
// means targetless.
type TransitionDefinition struct {
	Events    []Identifier      `json:"events,omitempty"`
	Targets   []Identifier      `json:"targets,omitempty"`
	Type      TransitionType    `json:"type,omitempty"`
	Condition *Expression       `json:"condition,omitempty"`
	Actions   []ExecutableBlock `json:"actions,omitempty"`
}

// InvokeDefinition contains invocation declaration data only. Src is a
// static source while SrcExpr is a datamodel expression; preserving both
// forms avoids making static source identity model-dependent. Content is one
// whole payload and is not a synthetic parameter map.
type InvokeDefinition struct {
	ID          Identifier        `json:"id,omitempty"`
	IDLocation  *Expression       `json:"idLocation,omitempty"`
	Type        string            `json:"type,omitempty"`
	TypeExpr    *Expression       `json:"typeExpr,omitempty"`
	Src         string            `json:"src,omitempty"`
	SrcExpr     *Expression       `json:"srcExpr,omitempty"`
	Params      []ParamDefinition `json:"params,omitempty"`
	Content     *Expression       `json:"content,omitempty"`
	AutoForward bool              `json:"autoForward,omitempty"`
	Finalize    []ExecutableBlock `json:"finalize,omitempty"`
}

// DoneDataDefinition computes the payload of a final state's done event.
// Params and Content are mutually exclusive; Content is one whole payload.
type DoneDataDefinition struct {
	Params  []ParamDefinition `json:"params,omitempty"`
	Content *Expression       `json:"content,omitempty"`
}

// Clone returns a deep, independently editable copy.
func (d Definition) Clone() Definition {
	clone := d
	clone.Data = cloneDataDefinitions(d.Data)
	clone.Root = d.Root.clone()
	return clone
}

func (s StateDefinition) clone() StateDefinition {
	clone := s
	clone.Initial = cloneTransition(s.Initial)
	clone.OnEntry = cloneBlocks(s.OnEntry)
	clone.OnExit = cloneBlocks(s.OnExit)
	clone.Data = cloneDataDefinitions(s.Data)
	if s.Transitions != nil {
		clone.Transitions = make([]TransitionDefinition, len(s.Transitions))
		for i := range s.Transitions {
			clone.Transitions[i] = s.Transitions[i].clone()
		}
	}
	if s.Invokes != nil {
		clone.Invokes = make([]InvokeDefinition, len(s.Invokes))
		for i := range s.Invokes {
			clone.Invokes[i] = s.Invokes[i].clone()
		}
	}
	if s.DoneData != nil {
		value := *s.DoneData
		value.Params = cloneParams(value.Params)
		value.Content = cloneExpression(value.Content)
		clone.DoneData = &value
	}
	if s.Children != nil {
		clone.Children = make([]StateDefinition, len(s.Children))
		for i := range s.Children {
			clone.Children[i] = s.Children[i].clone()
		}
	}
	return clone
}

func cloneTransition(transition *TransitionDefinition) *TransitionDefinition {
	if transition == nil {
		return nil
	}
	clone := transition.clone()
	return &clone
}

func (t TransitionDefinition) clone() TransitionDefinition {
	t.Events = append([]Identifier(nil), t.Events...)
	t.Targets = append([]Identifier(nil), t.Targets...)
	t.Condition = cloneExpression(t.Condition)
	t.Actions = cloneBlocks(t.Actions)
	return t
}

func (i InvokeDefinition) clone() InvokeDefinition {
	i.IDLocation = cloneExpression(i.IDLocation)
	i.TypeExpr = cloneExpression(i.TypeExpr)
	i.SrcExpr = cloneExpression(i.SrcExpr)
	i.Params = cloneParams(i.Params)
	i.Content = cloneExpression(i.Content)
	i.Finalize = cloneBlocks(i.Finalize)
	return i
}
