package statecharts

import (
	"context"
	"errors"
	"testing"
	"time"
)

func TestInvokeStartsOnStateEntryAndDeliversEvents(t *testing.T) {
	started := make(chan struct{})
	chart, err := Build(
		Compound("m", "waiting",
			Children(
				Atomic("waiting",
					Invoke(func(ctx context.Context, params any, io InvokeIO) (any, error) {
						close(started)
						io.Deliver(Event{Name: "ping"})
						<-ctx.Done()
						return nil, nil
					}),
					On("ping", Target("done")),
				),
				Atomic("done"),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	in := New(chart, nil)
	ctx := context.Background()
	if err := in.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer in.Stop(ctx)

	select {
	case <-started:
	case <-time.After(2 * time.Second):
		t.Fatalf("invoke never started")
	}

	// Synchronize with the actor goroutine: the invoke's "ping" arrives on
	// the external queue asynchronously, so send a no-op and rely on FIFO
	// ordering through the same inbox to know it was already processed --
	// same pattern as the delayed-send tests.
	deadline := time.Now().Add(2 * time.Second)
	for {
		if err := in.Send(ctx, Event{Name: "noop", Type: EventExternal}); err != nil {
			t.Fatalf("Send: %v", err)
		}
		if hasState(in.Configuration(), "done") {
			break
		}
		if time.Now().After(deadline) {
			t.Fatalf("configuration = %v, want 'done' after invoke delivered 'ping'", in.Configuration())
		}
		time.Sleep(time.Millisecond)
	}
}

func TestInvokeNotStartedIfStateExitedWithinSameMacrostep(t *testing.T) {
	var started bool
	chart, err := Build(
		Compound("m", "transient",
			Children(
				// An eventless transition fires immediately, before the
				// macrostep this state was entered in ever settles -- per
				// SCXML mainEventLoop, the invoke must never actually
				// start.
				Atomic("transient",
					Invoke(func(ctx context.Context, params any, io InvokeIO) (any, error) {
						started = true
						return nil, nil
					}),
					Eventless(Target("settled")),
				),
				Atomic("settled"),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	in := New(chart, nil)
	ctx := context.Background()
	if err := in.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer in.Stop(ctx)

	if !hasState(in.Configuration(), "settled") {
		t.Fatalf("configuration = %v, want 'settled'", in.Configuration())
	}
	if started {
		t.Fatalf("invoke started for a state that was exited within its own entering macrostep")
	}
}

func TestInvokeCancelledOnStateExitAndSuppressesDoneInvoke(t *testing.T) {
	cancelled := make(chan struct{})
	returned := make(chan struct{})
	chart, err := Build(
		Compound("m", "a",
			Children(
				Atomic("a",
					Invoke(func(ctx context.Context, params any, io InvokeIO) (any, error) {
						<-ctx.Done()
						close(cancelled)
						close(returned)
						return nil, nil
					}),
					On("go", Target("b")),
				),
				Atomic("b"),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	in := New(chart, nil)
	ctx := context.Background()
	if err := in.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer in.Stop(ctx)

	if err := in.Send(ctx, Event{Name: "go", Type: EventExternal}); err != nil {
		t.Fatalf("Send: %v", err)
	}

	select {
	case <-cancelled:
	case <-time.After(2 * time.Second):
		t.Fatalf("invoke was never cancelled when its containing state was exited")
	}
	<-returned

	// SCXML 6.4.3: a cancelled invocation MUST NOT generate done.invoke.
	// Give the (already-returned) goroutine's Deliver call, if it wrongly
	// fired, a moment to land, then confirm "b" never saw a transition.
	time.Sleep(20 * time.Millisecond)
	if err := in.Send(ctx, Event{Name: "noop", Type: EventExternal}); err != nil {
		t.Fatalf("Send: %v", err)
	}
	if !hasState(in.Configuration(), "b") {
		t.Fatalf("configuration = %v, want still 'b'", in.Configuration())
	}
}

func TestInvokeErrorBecomesCommunicationError(t *testing.T) {
	boom := errors.New("boom")
	gotErr := make(chan Event, 1)
	chart, err := Build(
		Compound("m", "a",
			Children(
				Atomic("a",
					Invoke(func(ctx context.Context, params any, io InvokeIO) (any, error) {
						return nil, boom
					}),
					On(string(ErrEventCommunication), Then(Action(func(d *struct{}, ec ExecContext) error {
						ev, _ := ec.Event()
						gotErr <- ev
						return nil
					}))),
				),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	in := New(chart, &struct{}{})
	ctx := context.Background()
	if err := in.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer in.Stop(ctx)

	select {
	case ev := <-gotErr:
		if ev.Data != boom {
			t.Fatalf("error.communication Data = %v, want %v", ev.Data, boom)
		}
	case <-time.After(2 * time.Second):
		t.Fatalf("never observed error.communication for a failing invoke")
	}
}

func TestInvokeAutoGeneratedIDFormat(t *testing.T) {
	gotID := make(chan Identifier, 1)
	chart, err := Build(
		Compound("m", "a",
			Children(
				Atomic("a",
					Invoke(func(ctx context.Context, params any, io InvokeIO) (any, error) {
						io.Deliver(Event{Name: "ping"})
						<-ctx.Done()
						return nil, nil
					}),
					On("ping", Then(Action(func(d *struct{}, ec ExecContext) error {
						ev, _ := ec.Event()
						gotID <- ev.InvokeID
						return nil
					}))),
				),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	in := New(chart, &struct{}{})
	ctx := context.Background()
	if err := in.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer in.Stop(ctx)

	select {
	case id := <-gotID:
		if want := Identifier("a.invoke1"); id != want {
			t.Fatalf("auto-generated InvokeID = %q, want %q", id, want)
		}
	case <-time.After(2 * time.Second):
		t.Fatalf("never observed the invoke's InvokeID on a delivered event")
	}
}

func TestInvokeSendTargetRoutesToIncoming(t *testing.T) {
	received := make(chan Event, 1)
	chart, err := Build(
		Compound("m", "a",
			Children(
				Atomic("a",
					Invoke(func(ctx context.Context, params any, io InvokeIO) (any, error) {
						select {
						case ev := <-io.Incoming:
							received <- ev
						case <-ctx.Done():
						}
						return nil, nil
					}, WithInvokeID("svc")),
					On("poke", Then(Action(func(d *struct{}, ec ExecContext) error {
						ec.Send("hello", SendOptions{Target: "#_svc", Data: 42})
						return nil
					}))),
				),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	in := New(chart, &struct{}{})
	ctx := context.Background()
	if err := in.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer in.Stop(ctx)

	if err := in.Send(ctx, Event{Name: "poke", Type: EventExternal}); err != nil {
		t.Fatalf("Send: %v", err)
	}

	select {
	case ev := <-received:
		if ev.Name != "hello" || ev.Data != 42 {
			t.Fatalf("invoke received %+v, want Name=hello Data=42", ev)
		}
	case <-time.After(2 * time.Second):
		t.Fatalf("invoke never received the #_svc-targeted send")
	}
}

// --- A "clock.pl"-style invoke: scxml.html's Appendix on <finalize>
// (6.5) walks through a state machine that invokes an external clock
// service (src="clock.pl"), receives periodic "ping" events carrying a
// 12-hour clock reading, and uses <finalize> to normalize that reading
// into a 24-hour value before a transition's guard inspects it -- so
// <finalize> runs strictly before transition selection, not after. This
// reproduces that scenario end to end, with a deterministic, in-process
// stand-in for clock.pl driven by a test-controlled feed instead of a
// real timer. ---------------------------------------------------------

// clockTick is what the invoked clock service reports each time it
// "ticks" -- the same fields scxml.html's example describes: an hour in
// 12-hour form, a flag for AM/PM, and the fact of a new second.
type clockTick struct {
	Hour int // 1-12
	IsAM bool
}

// clockService is a real, running goroutine: it forwards whatever ticks
// arrive on feed as "ping" events until either feed is closed (natural
// completion) or it's cancelled (the invoking state was exited).
func clockService(feed <-chan clockTick) InvokeFunc {
	return func(ctx context.Context, params any, io InvokeIO) (any, error) {
		for {
			select {
			case <-ctx.Done():
				return nil, nil
			case tick, ok := <-feed:
				if !ok {
					return nil, nil
				}
				io.Deliver(Event{Name: "ping", Data: tick})
			}
		}
	}
}

type store struct {
	Hour24 int
}

// normalizeTime is <finalize>'s content in scxml.html's example, verbatim:
// "time.setHours(_event.data.currentHour + (_event.isAm ? 0 : 12) - 1)".
// <finalize> runs for every event carrying its invocation's InvokeID
// (SCXML 6.5 matches by invokeid alone, not by event name), including the
// eventual done.invoke.timer -- whose Data is whatever clockService
// returned (nil here), not a clockTick -- so, like any real finalize
// handler massaging a specific payload shape, it must check first.
var normalizeTime = Action(func(s *store, ec ExecContext) error {
	ev, _ := ec.Event()
	tick, ok := ev.Data.(clockTick)
	if !ok {
		return nil
	}
	offset := 12
	if tick.IsAM {
		offset = 0
	}
	s.Hour24 = tick.Hour + offset - 1
	return nil
})

func buildClockChart(t *testing.T, feed <-chan clockTick) *Instance {
	t.Helper()
	afterHours := Cond(func(s *store, ec ExecContext) bool {
		return s.Hour24 > 17 || s.Hour24 < 9
	})

	chart, err := Build(
		Compound("root", "getTime",
			Children(
				Atomic("getTime",
					Invoke(clockService(feed), WithInvokeID("timer"), WithFinalize(normalizeTime)),
					On("ping", If(afterHours), Target("storeClosed")),
					On("ping", Target("takeOrder")),
					On("done.invoke.timer", Target("clockDone")),
				),
				Atomic("storeClosed"),
				Atomic("takeOrder"),
				Atomic("clockDone"),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	in := New(chart, &store{})
	ctx := context.Background()
	if err := in.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	return in
}

func TestInvokeClockFinalizeNormalizesBeforeGuardEvaluates(t *testing.T) {
	cases := []struct {
		name string
		tick clockTick
		want Identifier
	}{
		// 8 PM -> 19:00 -> after hours.
		{"evening", clockTick{Hour: 8, IsAM: false}, "storeClosed"},
		// 2 PM -> 13:00 -> open.
		{"afternoon", clockTick{Hour: 2, IsAM: false}, "takeOrder"},
		// 10 PM -> 21:00 -> after hours.
		{"night", clockTick{Hour: 10, IsAM: false}, "storeClosed"},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			feed := make(chan clockTick, 1)
			in := buildClockChart(t, feed)
			ctx := context.Background()
			defer in.Stop(ctx)

			feed <- c.tick

			deadline := time.Now().Add(2 * time.Second)
			for !hasState(in.Configuration(), c.want) {
				if err := in.Send(ctx, Event{Name: "noop", Type: EventExternal}); err != nil {
					t.Fatalf("Send: %v", err)
				}
				if time.Now().After(deadline) {
					t.Fatalf("configuration = %v, want %q", in.Configuration(), c.want)
				}
				time.Sleep(time.Millisecond)
			}
		})
	}
}

func TestInvokeClockDoneEventOnFeedClose(t *testing.T) {
	feed := make(chan clockTick)
	in := buildClockChart(t, feed)
	ctx := context.Background()
	defer in.Stop(ctx)

	close(feed) // the clock service returns (nil, nil): natural completion

	deadline := time.Now().Add(2 * time.Second)
	for !hasState(in.Configuration(), "clockDone") {
		if err := in.Send(ctx, Event{Name: "noop", Type: EventExternal}); err != nil {
			t.Fatalf("Send: %v", err)
		}
		if time.Now().After(deadline) {
			t.Fatalf("configuration = %v, want 'clockDone' after the clock's natural completion", in.Configuration())
		}
		time.Sleep(time.Millisecond)
	}
	if err := in.Err(); err != nil {
		t.Fatalf("Err() = %v, want nil", err)
	}
}

// --- Completing <invoke>: autoforward (SCXML 6.4.1) and "#_parent"
// (Appendix C.1), including a real child SCXML session via InvokeChart. --

func TestInvokeAutoForwardDeliversEveryExternalEvent(t *testing.T) {
	received := make(chan Event, 8)
	chart, err := Build(
		// "a" has no transitions at all: autoforward must still copy
		// every external event to the invocation regardless of whether
		// the chart itself has a matching transition for it.
		Atomic("a",
			Invoke(func(ctx context.Context, params any, io InvokeIO) (any, error) {
				for {
					select {
					case ev, ok := <-io.Incoming:
						if !ok {
							return nil, nil
						}
						received <- ev
					case <-ctx.Done():
						return nil, nil
					}
				}
			}, WithAutoForward()),
		),
	)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	in := New(chart, nil)
	ctx := context.Background()
	if err := in.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer in.Stop(ctx)

	if err := in.Send(ctx, Event{Name: "one", Type: EventExternal, Data: 1}); err != nil {
		t.Fatalf("Send: %v", err)
	}
	if err := in.Send(ctx, Event{Name: "two", Type: EventExternal, Data: 2}); err != nil {
		t.Fatalf("Send: %v", err)
	}

	want := []struct {
		name Identifier
		data int
	}{{"one", 1}, {"two", 2}}
	for _, w := range want {
		select {
		case ev := <-received:
			if ev.Name != w.name || ev.Data != w.data {
				t.Fatalf("forwarded event = %+v, want Name=%q Data=%d", ev, w.name, w.data)
			}
		case <-time.After(2 * time.Second):
			t.Fatalf("never received autoforwarded event %q", w.name)
		}
	}
}

func TestInvokeAutoForwardStopsAfterCancellation(t *testing.T) {
	received := make(chan Event, 8)
	chart, err := Build(
		Compound("m", "a",
			Children(
				Atomic("a",
					Invoke(func(ctx context.Context, params any, io InvokeIO) (any, error) {
						for {
							select {
							case ev, ok := <-io.Incoming:
								if !ok {
									return nil, nil
								}
								received <- ev
							case <-ctx.Done():
								return nil, nil
							}
						}
					}, WithAutoForward()),
					On("go", Target("b")),
				),
				Atomic("b"),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	in := New(chart, nil)
	ctx := context.Background()
	if err := in.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer in.Stop(ctx)

	if err := in.Send(ctx, Event{Name: "go", Type: EventExternal}); err != nil {
		t.Fatalf("Send: %v", err)
	}
	if !hasState(in.Configuration(), "b") {
		t.Fatalf("configuration = %v, want 'b'", in.Configuration())
	}

	// Whether "go" itself -- copied to the invocation as it was dequeued,
	// before the transition it triggered was even selected -- actually
	// got read by the invocation's own goroutine before that goroutine
	// noticed ctx cancelled is a genuine race (Go's select makes no
	// ordering promise between two simultaneously-ready cases), so it's
	// deliberately not asserted here. What must be deterministic is that
	// nothing sent after the invoking state is gone ever reaches it: by
	// the time "after" is processed, this invocation no longer appears in
	// invokesByID at all, so it's never even considered for forwarding,
	// regardless of goroutine scheduling on the reading side.
	if err := in.Send(ctx, Event{Name: "after", Type: EventExternal}); err != nil {
		t.Fatalf("Send: %v", err)
	}
	drainDeadline := time.After(200 * time.Millisecond)
	for {
		select {
		case ev := <-received:
			if ev.Name == "after" {
				t.Fatalf("received %+v after the invoking state was exited; autoforward should have stopped", ev)
			}
		case <-drainDeadline:
			return
		}
	}
}

// childPingPongChart is a small, complete SCXML session in its own right:
// it greets whatever invoked it over "#_parent" on entry, and replies
// "pong" the same way once it's forwarded a "ping".
func childPingPongChart(t *testing.T) *Chart {
	t.Helper()
	chart, err := Build(
		Compound("croot", "start",
			Children(
				Atomic("start",
					OnEntry(Action(func(d *struct{}, ec ExecContext) error {
						ec.Send("hello", SendOptions{Target: "#_parent", Data: "hi"})
						return nil
					})),
					On("ping", Target("pinged")),
				),
				Atomic("pinged",
					OnEntry(Action(func(d *struct{}, ec ExecContext) error {
						ec.Send("pong", SendOptions{Target: "#_parent"})
						return nil
					})),
				),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build(child): %v", err)
	}
	return chart
}

// TestInvokeChartRoundTripsThroughParentAndAutoForward reproduces SCXML
// 6.4's full invoking-chart-is-the-parent picture end to end: a real
// child *Chart* is invoked as a genuine child session (InvokeChart), its
// own <send target="#_parent"> reaches back into the parent (Appendix
// C.1), and the parent's autoforward relays an external event down to the
// child with no explicit "#_<invokeid>" addressing needed.
func TestInvokeChartRoundTripsThroughParentAndAutoForward(t *testing.T) {
	childChart := childPingPongChart(t)

	parentChart, err := Build(
		Compound("proot", "invoking",
			Children(
				// "invoking" (not its inner children) holds the Invoke,
				// so the child session's lifetime spans the whole
				// hello/ping/pong handshake -- only the final transition
				// to "done" (which leaves "invoking" altogether) cancels
				// it.
				Compound("invoking", "waitingHello",
					Children(
						Atomic("waitingHello", On("hello", Target("waitingPong"))),
						Atomic("waitingPong", On("pong", Target("done"))),
					),
					Invoke(
						InvokeChart(childChart, func(params any) any { return &struct{}{} }, nil),
						WithInvokeID("child"),
						WithAutoForward(),
					),
				),
				Atomic("done"),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build(parent): %v", err)
	}

	parent := New(parentChart, nil)
	ctx := context.Background()
	if err := parent.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer parent.Stop(ctx)

	deadline := time.Now().Add(2 * time.Second)
	for !hasState(parent.Configuration(), "waitingPong") {
		if time.Now().After(deadline) {
			t.Fatalf("configuration = %v, want 'waitingPong' after the child's #_parent 'hello'", parent.Configuration())
		}
		time.Sleep(time.Millisecond)
	}

	// The parent has no transition of its own for "ping" -- it only
	// reaches the child via autoforward, with no explicit
	// "#_<invokeid>" addressing on the parent's part.
	if err := parent.Send(ctx, Event{Name: "ping", Type: EventExternal}); err != nil {
		t.Fatalf("Send: %v", err)
	}

	deadline = time.Now().Add(2 * time.Second)
	for !hasState(parent.Configuration(), "done") {
		if time.Now().After(deadline) {
			t.Fatalf("configuration = %v, want 'done' after the child's #_parent 'pong'", parent.Configuration())
		}
		time.Sleep(time.Millisecond)
	}
}

// TestInvokeChartExplicitSendReachesChildWithoutAutoForward exercises the
// other half of SCXML 6.4.4's addressing -- SendOptions{Target:
// "#_<invokeid>"} without WithAutoForward -- against the same real child
// session.
func TestInvokeChartExplicitSendReachesChildWithoutAutoForward(t *testing.T) {
	childChart := childPingPongChart(t)

	parentChart, err := Build(
		Compound("proot", "invoking",
			Children(
				Compound("invoking", "waitingHello",
					Children(
						Atomic("waitingHello",
							On("hello", Target("waitingPong"), Then(Action(func(d *struct{}, ec ExecContext) error {
								ec.Send("ping", SendOptions{Target: "#_child"})
								return nil
							}))),
						),
						Atomic("waitingPong", On("pong", Target("done"))),
					),
					Invoke(
						InvokeChart(childChart, func(params any) any { return &struct{}{} }, nil),
						WithInvokeID("child"),
					),
				),
				Atomic("done"),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build(parent): %v", err)
	}

	parent := New(parentChart, &struct{}{})
	ctx := context.Background()
	if err := parent.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer parent.Stop(ctx)

	deadline := time.Now().Add(2 * time.Second)
	for !hasState(parent.Configuration(), "done") {
		if time.Now().After(deadline) {
			t.Fatalf("configuration = %v, want 'done' (hello -> explicit #_child ping -> child's #_parent pong)", parent.Configuration())
		}
		time.Sleep(time.Millisecond)
	}
}

// TestInvokeChartCancelledOnStateExitStopsChildSession confirms the child
// session is a real Instance subject to the same exitInterpreter cleanup
// as any other -- cancelling the invocation must actually stop it, not
// leave it running orphaned.
func TestInvokeChartCancelledOnStateExitStopsChildSession(t *testing.T) {
	childExited := make(chan struct{})
	childChart, err := Build(
		Atomic("only",
			OnExit(Action(func(d *struct{}, ec ExecContext) error {
				close(childExited)
				return nil
			})),
		),
	)
	if err != nil {
		t.Fatalf("Build(child): %v", err)
	}

	parentChart, err := Build(
		Compound("m", "a",
			Children(
				Atomic("a",
					Invoke(InvokeChart(childChart, func(params any) any { return &struct{}{} }, nil)),
					On("go", Target("b")),
				),
				Atomic("b"),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build(parent): %v", err)
	}

	parent := New(parentChart, nil)
	ctx := context.Background()
	if err := parent.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer parent.Stop(ctx)

	if err := parent.Send(ctx, Event{Name: "go", Type: EventExternal}); err != nil {
		t.Fatalf("Send: %v", err)
	}

	select {
	case <-childExited:
	case <-time.After(2 * time.Second):
		t.Fatalf("child session was never stopped when the invoking state was exited")
	}
}

// TestInvokeChartChildIOProcessorsReflectBaseIOWithoutParentEntry confirms
// parentIOProcessor.IOProcessors forwards baseIO's advertised entries into
// the child session's own ExecContext, and never synthesizes a "#_parent"
// entry -- _ioprocessors describes how others reach this session, and
// "#_parent" is the reverse (how the child reaches its parent).
func TestInvokeChartChildIOProcessorsReflectBaseIOWithoutParentEntry(t *testing.T) {
	seen := make(chan []IOProcessorInfo, 1)
	childChart, err := Build(
		Atomic("only",
			OnEntry(Action(func(d *struct{}, ec ExecContext) error {
				seen <- ec.IOProcessors()
				return nil
			})),
		),
	)
	if err != nil {
		t.Fatalf("Build(child): %v", err)
	}

	baseIO := &describingIOProcessor{infos: []IOProcessorInfo{{Type: "mock", Location: "mock://base"}}}
	parentChart, err := Build(
		Compound("m", "a",
			Children(
				Atomic("a", Invoke(InvokeChart(childChart, func(params any) any { return &struct{}{} }, baseIO))),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build(parent): %v", err)
	}

	parent := New(parentChart, nil)
	ctx := context.Background()
	if err := parent.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer parent.Stop(ctx)

	select {
	case got := <-seen:
		if len(got) != 1 || got[0].Type != "mock" || got[0].Location != "mock://base" {
			t.Fatalf("child ExecContext.IOProcessors() = %v, want [{mock mock://base}] (baseIO's entries, no synthetic #_parent entry)", got)
		}
	case <-time.After(2 * time.Second):
		t.Fatalf("child's OnEntry action never ran")
	}
}

// TestInvokeChartChildIOProcessorsEmptyWithNilBaseIO confirms a nil baseIO
// (InvokeChart's own "defer to NoopIOProcessor" default) leaves the child
// with nothing to advertise, mirroring a bare Instance with no IOProcessor
// configured.
func TestInvokeChartChildIOProcessorsEmptyWithNilBaseIO(t *testing.T) {
	seen := make(chan []IOProcessorInfo, 1)
	childChart, err := Build(
		Atomic("only",
			OnEntry(Action(func(d *struct{}, ec ExecContext) error {
				seen <- ec.IOProcessors()
				return nil
			})),
		),
	)
	if err != nil {
		t.Fatalf("Build(child): %v", err)
	}

	parentChart, err := Build(
		Compound("m", "a",
			Children(
				Atomic("a", Invoke(InvokeChart(childChart, func(params any) any { return &struct{}{} }, nil))),
			),
		),
	)
	if err != nil {
		t.Fatalf("Build(parent): %v", err)
	}

	parent := New(parentChart, nil)
	ctx := context.Background()
	if err := parent.Start(ctx); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer parent.Stop(ctx)

	select {
	case got := <-seen:
		if len(got) != 0 {
			t.Fatalf("child ExecContext.IOProcessors() = %v, want empty (nil baseIO has nothing to advertise)", got)
		}
	case <-time.After(2 * time.Second):
		t.Fatalf("child's OnEntry action never ran")
	}
}
